### ISSUE TITLE
I can not use the 0.12.0

### ISSUE THREAD

**Issue by badboy-tian** [luanpotter/audioplayers#172]
```
Because flutter_cache_manager 0.3.2 depends on path_provider ^0.5.0+1 and no versions of flutter_cache_manager match >0.3.2 <0.4.0, flutter_cache_manager ^0.3.2 requires path_provider ^0.5.0+1.
And because audioplayers >=0.12.0 depends on path_provider ^1.1.0, audioplayers >=0.12.0 is incompatible with flutter_cache_manager ^0.3.2.
And because cached_network_image 0.8.0 depends on flutter_cache_manager ^0.3.2 and no versions of cached_network_image match >0.8.0 <0.9.0, audioplayers >=0.12.0 is incompatible with cached_network_image ^0.8.0.
So, because voicechanger_app depends on both cached_network_image ^0.8.0 and audioplayers ^0.12.0, version solving failed.
pub get failed (1)
```

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  cached_network_image: ^0.8.0
  dio: ^2.1.3
  intl: ^0.15.8
  photo_view: ^0.3.3
  permission_handler: '^3.0.0'
  audioplayers: ^0.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
```
