### ISSUE TITLE
playBytes() not supported on iOS?

### ISSUE THREAD

**Issue by andreclinio** [luanpotter/audioplayers#848]
First of all, let me congratulate developers for the nice idea of audioplayers...

My flutter project with audioplayers works nicely on Android now. However, I have tried (for the first time) to run it on iOS.
While running my app inside the emulator, I got the following message:
```
Unhandled Exception: PlatformException(Not supported, Only Android is currently supported, null, null)
#0      AudioPlayer.playBytes (package:audioplayers/audioplayers.dart:374:7)
(...)
```

And when running in a real iPhone8 device, nothing happens...

As I could not see any restrictions at the docs, I would ask if this imitation really exists now or if it is a new bug (as I have already used audioplayers before on iOS -- not with playBytes actually).

My project settings are:
```
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
  flutter:
    sdk: flutter
  
  audioplayers: ^0.18.3
 ```
 
 
 Actually, I gave tried playBytes() as I need to play a mp3 file with a local asset file. I read all bytes and play. If someone has some solution for it (web, ios and android), I would appreciate any suggestions.
