### ISSUE TITLE
Compilation error when building: WrappedMediaPlayer redeclaration

### ISSUE THREAD

**Issue by amicharski** [luanpotter/audioplayers#930]
**Description**
I'm upgrading from 0.18.0 to 0.19.0, and while doing so I got this compilation error when trying to build.

**Pubspec**
```yaml
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: 0.19.0
  google_mobile_ads: ^0.12.0 #downgrade from 0.13.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2
  provider: ^5.0.0
  gestures: ^0.0.1
  path_provider: ^2.0.2
  confetti: ^0.5.4+1
  firebase_admob: ^0.11.0+1
```

**Log Errors**
```
Running Gradle task 'assembleDebug'...
e: C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\audioplayers-0.18.3\android\src\main\kotlin\xyz\luan\audioplayers\WrappedMediaPlayer.kt: (8, 7): Redeclaration: WrappedMediaPlayer
e: C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\audioplayers-0.19.0\android\src\main\kotlin\xyz\luan\audioplayers\WrappedMediaPlayer.kt: (8, 7): Redeclaration: WrappedMediaPlayer

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audioplayers:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Platforms**
* OS: Android
* OS version: 11
* Device: Emulator
* flutter version: Flutter 2.3.0-16.0.pre • channel dev 
* audioplayers version: 0.19.0
* release or not release: debug
